### ISSUE TITLE
现代JavaScript高级教程似乎有一处错误

### ISSUE THREAD

**Issue by sun-unc** [linwu-hi/coding-time#164]
第5节-对象的隐式中
```javascript
let obj = { value: 42 };
let num = obj.valueOf();
console.log(num); // 输出: 42
``` 
正确的输出应该是{value:42}

**Comment by linwu-hi** [comment]
> 第5节-对象的隐式中
> 
> ```js
> let obj = { value: 42 };
> let num = obj.valueOf();
> console.log(num); // 输出: 42
> ```
> 
> 正确的输出应该是{value:42}
嗯嗯，感谢提醒，我明天修改或者你来个pr也行哈哈

**Comment by linwu-hi** [comment]
> 第5节-对象的隐式中
> 
> ```js
> let obj = { value: 42 };
> let num = obj.valueOf();
> console.log(num); // 输出: 42
> ```
> 
> 正确的输出应该是{value:42}

已更新补充，可以刷新一下页面🌹
